# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'beamUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
import numpy as np
from PyQt5.QtWidgets import QWidget, QVBoxLayout
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas

class MplWidget(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent) 
        self.figure = Figure() 
        self.canvas = FigureCanvas(self.figure)
        self.layout = QVBoxLayout(self)
        self.layout.addWidget(self.canvas)
        self.ax = self.figure.add_subplot(111)
        self.figure.tight_layout()
        self.ax.set_position([0, 0, 1, 1])  # Set the position to cover the entire figure

    def plot_wave(self,z):
        self.ax.clear()
        extent = [-6, 6, 0, 10]
        self.ax.imshow(z, extent=extent, aspect='equal', 
                    cmap='jet', origin='lower')
        self.ax.set_xlabel('x (m)')
        self.ax.set_ylabel('y (m)')
        self.ax.axis('off')
        self.canvas.figure.patch.set_facecolor('#2E3440')
        self.canvas.draw()

class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1218, 692)
        MainWindow.setStyleSheet("/* General QWidget Style */\n"
"QWidget {\n"
"    background-color: #2E3440;\n"
"    color: #D8DEE9;\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"/* PushButtons */\n"
"QPushButton {\n"
"    background-color: #4C566A;\n"
"    color: #ECEFF4;\n"
"    border: 1px solid #81A1C1;\n"
"    border-radius: 5px;\n"
"    padding: 5px 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #81A1C1;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #5E81AC;\n"
"}\n"
"\n"
"/* SpinBoxes */\n"
"QSpinBox {\n"
"    background-color: #3B4252;\n"
"    color: #ECEFF4;\n"
"    border: 1px solid #81A1C1;\n"
"    border-radius: 3px;\n"
"    padding: 2px;\n"
"}\n"
"QSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"    width: 12px;\n"
"    border-left: 1px solid #81A1C1;\n"
"}\n"
"QSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"    width: 12px;\n"
"    border-left: 1px solid #81A1C1;\n"
"}\n"
"\n"
"/* Horizontal Sliders */\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #81A1C1;\n"
"    height: 5px;\n"
"    background: #3B4252;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: #81A1C1;\n"
"    border: 1px solid #5E81AC;\n"
"    width: 15px;\n"
"    margin: -5px 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    color: #ECEFF4;\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* CheckBoxes */\n"
"QCheckBox {\n"
"    color: #ECEFF4;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    border: 1px solid #81A1C1;\n"
"    background-color: #2E3440;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #81A1C1;\n"
"    border: 1px solid #5E81AC;\n"
"}\n"
"\n"
"/* ComboBoxes */\n"
"QComboBox {\n"
"    background-color: #3B4252;\n"
"    color: #ECEFF4;\n"
"    border: 1px solid #81A1C1;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #3B4252;\n"
"    color: #ECEFF4;\n"
"    border: 1px solid #81A1C1;\n"
"}\n"
"\n"
"/* LCD Number */\n"
"QLCDNumber {\n"
"    background-color: #3B4252;\n"
"    color: #81A1C1;\n"
"    border: 2px solid #81A1C1;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* QPolarChart */\n"
"QPolarChart {\n"
"    background: transparent;\n"
"}\n"
"QPolarChart > .chart-title {\n"
"    color: #ECEFF4;\n"
"    font-size: 14pt;\n"
"    font-weight: bold;\n"
"}\n"
"QPolarChart > .axis-title {\n"
"    color: #D8DEE9;\n"
"}\n"
"\n"
"/* Scrollbars */\n"
"QScrollBar:horizontal, QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #2E3440;\n"
"    width: 8px;\n"
"    margin: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal, QScrollBar::handle:vertical {\n"
"    background: #4C566A;\n"
"    min-width: 20px;\n"
"    min-height: 20px;\n"
"}\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    background: none;\n"
"    border: none;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BeamPatternGraph = MplWidget(self.centralwidget)
        self.BeamPatternGraph.setObjectName("BeamPatternGraph")
        self.horizontalLayout.addWidget(self.BeamPatternGraph)
        self.WavesGraph = MplWidget(self.centralwidget)
        self.WavesGraph.setObjectName("WavesGraph")
        self.horizontalLayout.addWidget(self.WavesGraph)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.steeringAngleSpin = QtWidgets.QSpinBox(self.centralwidget)
        self.steeringAngleSpin.setObjectName("steeringAngleSpin")
        self.horizontalLayout_11.addWidget(self.steeringAngleSpin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.spacingSpin = QtWidgets.QSpinBox(self.centralwidget)
        self.spacingSpin.setObjectName("spacingSpin")
        self.horizontalLayout_12.addWidget(self.spacingSpin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.curvedCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.curvedCheckBox.setObjectName("curvedCheckBox")
        self.verticalLayout_6.addWidget(self.curvedCheckBox)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(100, 100))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.radiusSlider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radiusSlider.sizePolicy().hasHeightForWidth())
        self.radiusSlider.setSizePolicy(sizePolicy)
        self.radiusSlider.setMinimumSize(QtCore.QSize(100, 0))
        self.radiusSlider.setOrientation(QtCore.Qt.Horizontal)
        self.radiusSlider.setObjectName("radiusSlider")
        self.horizontalLayout_10.addWidget(self.radiusSlider)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.selectTransmitterComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.selectTransmitterComboBox.setObjectName("selectTransmitterComboBox")
        self.horizontalLayout_3.addWidget(self.selectTransmitterComboBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.magnitudeSpin = QtWidgets.QSpinBox(self.centralwidget)
        self.magnitudeSpin.setObjectName("magnitudeSpin")
        self.horizontalLayout_9.addWidget(self.magnitudeSpin)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.frequencySpin = QtWidgets.QSpinBox(self.centralwidget)
        self.frequencySpin.setObjectName("frequencySpin")
        self.horizontalLayout_8.addWidget(self.frequencySpin)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.phaseShiftSpin = QtWidgets.QSpinBox(self.centralwidget)
        self.phaseShiftSpin.setObjectName("phaseShiftSpin")
        self.horizontalLayout_6.addWidget(self.phaseShiftSpin)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.transmitterNumLCD = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transmitterNumLCD.sizePolicy().hasHeightForWidth())
        self.transmitterNumLCD.setSizePolicy(sizePolicy)
        self.transmitterNumLCD.setMinimumSize(QtCore.QSize(70, 0))
        self.transmitterNumLCD.setMaximumSize(QtCore.QSize(5000, 50))
        self.transmitterNumLCD.setObjectName("transmitterNumLCD")
        self.horizontalLayout_7.addWidget(self.transmitterNumLCD)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.decreaseNumButton = QtWidgets.QPushButton(self.centralwidget)
        self.decreaseNumButton.setObjectName("decreaseNumButton")
        self.horizontalLayout_5.addWidget(self.decreaseNumButton)
        self.increaseNumButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.increaseNumButton.sizePolicy().hasHeightForWidth())
        self.increaseNumButton.setSizePolicy(sizePolicy)
        self.increaseNumButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.increaseNumButton.setObjectName("increaseNumButton")
        self.horizontalLayout_5.addWidget(self.increaseNumButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1218, 34))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Angle"))
        self.label_7.setText(_translate("MainWindow", "Spacing"))
        self.curvedCheckBox.setText(_translate("MainWindow", "Curved"))
        self.label_8.setText(_translate("MainWindow", "Radius"))
        self.label_5.setText(_translate("MainWindow", "                   Transmitter"))
        self.label_10.setText(_translate("MainWindow", "Magnitude"))
        self.label_9.setText(_translate("MainWindow", "Frequency"))
        self.label_3.setText(_translate("MainWindow", "Phase Shift"))
        self.label.setText(_translate("MainWindow", "Num of transmitters"))
        self.decreaseNumButton.setText(_translate("MainWindow", "Decrease"))
        self.increaseNumButton.setText(_translate("MainWindow", "Increase"))
